version: 2
executorType: docker
containerInfo:
  - image: rohara/pantheon:0.2
    env:
      - TERMINUS_ENV=ci{{$CIRCLE_BUILD_NUM}}
      - TERMINUS_SITE=migrate-pantheon-d8
      - PANTHEON_D7_SITE=migrate-pantheon-d7
      - PANTHEON_D7_BRANCH=dev
stages:
  build:
    workDir: /root/migrate_pantheon
    steps:
      - type: checkout
      - type: cache-restore
        key: migrate-pantheon-{{ .Branch }}-{{ checksum "composer.lock" }}
      - type: shell
        command: |
          composer install --no-interaction
          terminus auth login --machine-token=$TerminusToken
      - type: shell
        command: |
          # Make a new multidev env from a vanilla D8 site.
          cd tests/circle && ./create-fresh-d8-site.sh

          # Set up the D8 site with contrib migrate contrib modules and enable
          # those modules on Panetheon.
          cd tests/circle && ./setup-d8-repo.sh

          # Configure the migration, creating exportable, re-runnable configuration.
          cd tests/circle && ./configure-migrations.sh

          # Run the actual migration on Pantheon.
          cd tests/circle && ./run-migration-on-pantheon.sh

          # Check that a node actually migrated.
          cd tests/circle && ./verify-migration-succeeded.sh
      - type: cache-save
        key: migrate-pantheon-{{ .Branch }}-{{ checksum "composer.lock" }}
        paths:
          -  /root/.composer/cache
