#!/bin/bash

# Execute the Drupal 7 to Drupal 8 migration

export D7_DB_DATABASE=$(terminus site connection-info  --site=migrate-pantheon-d7  --env=dev  --field=mysql_database)
export D7_DB_USERNAME=$(terminus site connection-info --site=migrate-pantheon-d7  --env=dev --field=mysql_username)
export D7_DB_PASSWORD=$(terminus site connection-info --site=migrate-pantheon-d7  --env=dev --field=mysql_password)
export D7_DB_HOST=$(terminus site connection-info --site=migrate-pantheon-d7  --env=dev --field=mysql_host)
export D7_DB_PORT=$(terminus site connection-info --site=migrate-pantheon-d7  --env=dev --field=mysql_port)
terminus site wake --site=migrate-pantheon-d7 --env=dev
terminus drush  --site=migrate-pantheon-d8  --env=$PANTHEON_BRANCH  "migrate-upgrade  --legacy-db-url='mysql://$D7_DB_USERNAME:$D7_DB_PASSWORD@$D7_DB_HOST:$D7_DB_PORT/$D7_DB_DATABASE'  "
