#!/bin/bash

# Clone D8 code
git clone $(terminus site connection-info --field=git_url --site=$PANTHEON_SITE  --env=$PANTHEON_BRANCH) ~/drupal8 --branch=$PANTHEON_BRANCH

# Tell Composer where to find packages.
cd ~/drupal8 && composer config repositories.drupal composer https://packagist.drupal-composer.org

cd ~/drupal8 && composer require drupal/migrate_plus --prefer-dist
cd ~/drupal8 && composer require drupal/migrate_tools --prefer-dist
cd ~/drupal8 && composer require drupal/migrate_upgrade --prefer-dist

# Make a git commit
git config --global user.email "$GitEmail"
git config --global user.name "Circle CI Migration Automation"
cd ~/drupal8 && git add . &&  git commit -m 'Result of build step' && git push

# Clear caches to take up time before attempting to enable the modules.
terminus drush  --site=migrate-pantheon-d8  --env=$PANTHEON_BRANCH  "cr"
terminus drush  --site=migrate-pantheon-d8  --env=$PANTHEON_BRANCH  "en -y  migrate_plus migrate_tools migrate_upgrade"
terminus drush  --site=migrate-pantheon-d8  --env=$PANTHEON_BRANCH  "migrate-upgrade  --legacy-db-url='mysql://$D7_DB_USERNAME:$D7_DB_PASSWORD@$D7_DB_HOST:$D7_DB_PORT/$D7_DB_DATABASE'  "
