#!/bin/bash

# Bring the code down to Circle so that modules can be added via composer.
git clone $(terminus site connection-info --field=git_url --site=$PANTHEON_SITE  --env=$PANTHEON_BRANCH) ~/drupal8 --branch=$PANTHEON_BRANCH

# Tell Composer where to find packages.
cd ~/drupal8 && composer config repositories.drupal composer https://packagist.drupal-composer.org

cd ~/drupal8 && composer require drupal/migrate_plus8.2.x-dev --prefer-dist
cd ~/drupal8 && composer require drupal/migrate_tools8.2.x-dev --prefer-dist
cd ~/drupal8 && composer require drupal/migrate_upgrade:8.2.x-dev --prefer-dist
cd ~/drupal8 && composer require cweagans/composer-patches --prefer-dist

cp fixtures/settings.migrate-on-pantheon.php ~/drupal8/sites/default/settings.migrate-on-pantheon.php
cat fixtures/settings.php.addition >> ~/drupal8/sites/default/settings.php

# Update migrate_upgrade now that a patch is in place.
composer update drupal/migrate_upgrade

# Make a git commit
git config --global user.email "$GitEmail"
git config --global user.name "Circle CI Migration Automation"
cd ~/drupal8 && git add . &&  git commit -m 'Result of build step' && git push
