#!/bin/bash

# Tell Composer where to find packages.
cd ~/drupal8 && composer config repositories.drupal composer https://packagist.drupal-composer.org

cd ~/drupal8 && composer require drupal/migrate_plus --prefer-dist
cd ~/drupal8 && composer require drupal/migrate_tools --prefer-dist
cd ~/drupal8 && composer require drupal/migrate_upgrade --prefer-dist

# Make a git commit
git config --global user.email "$GitEmail"
git config --global user.name "Circle CI Migration Automation"
cd ~/drupal8 && git add . &&  git commit -m 'Result of build step' && git push

terminus site wake --site=migrate-pantheon-d7 --env=dev
export D7_DB_CONNECTION_STRING=$(terminus site connection-info --site=migrate-pantheon-d7  --env=dev --field=mysql_url)

terminus drush  --site=migrate-pantheon-d8  --env=$PANTHEON_BRANCH  "cr"
terminus drush  --site=migrate-pantheon-d8  --env=$PANTHEON_BRANCH  "en -y  migrate_plus migrate_tools migrate_upgrade"
terminus drush  --site=migrate-pantheon-d8  --env=$PANTHEON_BRANCH  "migrate-upgrade  --legacy-db-url=$D7_DB_CONNECTION_STRING"
